{
  "target": "https://domains.test",
  "summary": {
    "reachable": false,
    "error": "HTTPSConnectionPool(host='domains.test', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7a9bbda0cd70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  "details": {}
}
